### PR TITLE
Fixing bt_navigator on configuration file

### PR DESCRIPTION
**Pull request by andrejpadilha2**
Just copied the most up to date `nav2_params.yaml` file and changed the _footprint_ related to the following tutorial: https://navigation.ros.org/setup_guides/footprint/setup_footprint.html

### CODE REVIEW

**Comment by SteveMacenski** [comment]
This removed alot of relevant stuff - I'm not sure this is appropriate to merge. What's the specific change you made to fix an issue?

**Comment by andrejpadilha2** [comment]
Just changed it. I removed the least amount of lines that I could; manually tested each version. The libraries that gave me errors under `plug_lib_names` I removed.

**Comment by SteveMacenski** [comment]
What ROS distribution are you using? All of those BT nodes should be fine to use (and some are in use by default)

**Comment by andrejpadilha2** [comment]
That's interesting. I am running Foxy, on Ubuntu 20.0.4. The package's `nav2_params.yaml` file do not include those as well.

**Comment by SteveMacenski** [comment]
Ah I see then, these files are targeting `rolling` or the bleeding edge of development, not Foxy. Much has changed since then

**Pull request closed without merging**
