### PR TITLE
Support Speed Filter in costmap filters demo

### PR DESCRIPTION
**Pull request by AlexeyMerzlyakov**
- Rename the package from `nav2_keepout_filter_demo` -> to `nav2_costmap_filters_demo` to be universal for all costmap filters.
- Added Speed Filter stuff support to `nav2_costmap_filters_demo`.

The main task is: https://github.com/ros-planning/navigation.ros.org/issues/123.

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
But should there be a new launch file for this to use the other speed filter map? Or a config file to enable speed filter for that tutorial?

**Comment by AlexeyMerzlyakov** [comment]
In both cases (keepouts and speed limits) the logic of launch-file remain to be the same: we are launching costmap info server + map server publishing mask file.

Therefore, I left only one launch-file for both tutorials. It is being parametrized by `params_file` and `mask` input params.
E.g. for speed filter it will be something like:
```
ros2 launch nav2_costmap_filters_demo costmap_filter_info.launch.py params_file:=.../params/speed_params.yaml mask:=.../maps/speed_mask.yaml
```

And for keepouts we are just using another parameters:
```
ros2 launch nav2_costmap_filters_demo costmap_filter_info.launch.py params_file:=.../params/keepout_params.yaml mask:=.../maps/keepout_mask.yaml
```

Keepout is going by-default. I believe, we do not need to separate this launch into two files having the same logic.

**Comment by SteveMacenski** [comment]
Ok, can we remove the  defaults then? If the tutorials for both will define a path, it would make be feel better without defaults in the code since there isn't really a preference for one or other and makes the user have to consciously pick one. I can foresee tickets about how its reading the wrong parameters and they don't know why

**Comment by AlexeyMerzlyakov** [comment]
> Ok, can we remove the defaults then?

Sure. Done in https://github.com/ros-planning/navigation2_tutorials/pull/18/commits/ee65df147936dabd1a5a9df61b83a947cefd7d98.

**Review by SteveMacenski — APPROVED** [review]

**Pull request merged**
