### PR TITLE
Update sam_bot_description.urdf

### PR DESCRIPTION
**Pull request by liangyuwei-ai**
Fix inertia setting of the chassis(base_link) and wheels, and fix the negative radius of caster(front_caster link).

### CODE REVIEW

**Comment by liangyuwei-ai** [comment]
Fixed this issue #26

**Comment by SteveMacenski** [comment]
@jd-deleon can you verify this is correct?

**Comment by jd-deleon** [comment]
Yup, it looks good. I'll file a separate PR in the navigation.ros.org website to reflect the update. Thanks for catching this :)

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Thank you @liangyuwei-ai and @jd-deleon for the update and quick response!

**Pull request merged**
